version: "3.8"
services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: events_storage
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - app_network
    healthcheck:
       test: [ "CMD", "mysqladmin", "-u", "root", "-proot", "ping", "-h", "localhost", "-P3306"]
       timeout: 20s
       retries: 10

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

